
export {default as Home} from './home/home.page'
export {default as MainLayout} from './layout/layout.page'
export {default as About} from './about/about.page'
export {default as Shop} from './shop/shop.page'
export {default as Panier} from './panier/panier.page'
export {default as Commande} from './commande/commande.page'
export {default as Contact} from './contact/contact.page'
export {default as Login} from './cnx/login.page'
export {default as Register} from './cnx/register.page'